// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfdefcam[] =
"<?xml version=\"1.0\"?>"
"<!-- pfdefcam.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.defaultcamera</name>"
"        <implementation>celPfDefaultCamera</implementation>"
"	<description>CEL Default Camera Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfDefaultCamera_FACTORY_REGISTER_DEFINED 
  #define celPfDefaultCamera_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfDefaultCamera) 
  #endif

class pfdefcam
{
SCF_REGISTER_STATIC_LIBRARY(pfdefcam,metainfo_pfdefcam)
  #ifndef celPfDefaultCamera_FACTORY_REGISTERED 
  #define celPfDefaultCamera_FACTORY_REGISTERED 
    celPfDefaultCamera_StaticInit celPfDefaultCamera_static_init__; 
  #endif
public:
 pfdefcam();
};
pfdefcam::pfdefcam() {}

}
