// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfjump[] =
"<?xml version=\"1.0\"?>"
"<!-- pfjump.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.move.jump</name>"
"        <implementation>celPfJump</implementation>"
"        <description>CEL Jump Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfJump_FACTORY_REGISTER_DEFINED 
  #define celPfJump_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfJump) 
  #endif

class pfjump
{
SCF_REGISTER_STATIC_LIBRARY(pfjump,metainfo_pfjump)
  #ifndef celPfJump_FACTORY_REGISTERED 
  #define celPfJump_FACTORY_REGISTERED 
    celPfJump_StaticInit celPfJump_static_init__; 
  #endif
public:
 pfjump();
};
pfjump::pfjump() {}

}
