// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_lootmgr[] =
"<?xml version=\"1.0\"?>"
"<!-- elcm.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.tools.lootmanager</name>"
"        <implementation>celLootManager</implementation>"
"        <description>CEL Loot Manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celLootManager_FACTORY_REGISTER_DEFINED 
  #define celLootManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celLootManager) 
  #endif

class lootmgr
{
SCF_REGISTER_STATIC_LIBRARY(lootmgr,metainfo_lootmgr)
  #ifndef celLootManager_FACTORY_REGISTERED 
  #define celLootManager_FACTORY_REGISTERED 
    celLootManager_StaticInit celLootManager_static_init__; 
  #endif
public:
 lootmgr();
};
lootmgr::lootmgr() {}

}
