// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_blxml[] =
"<?xml version=\"1.0\"?>"
"<!-- blxml.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.behaviourlayer.xml</name>"
"        <implementation>celBlXml</implementation>"
"	<description>CEL XML Behaviour Layer</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celBlXml_FACTORY_REGISTER_DEFINED 
  #define celBlXml_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celBlXml) 
  #endif

class blxml
{
SCF_REGISTER_STATIC_LIBRARY(blxml,metainfo_blxml)
  #ifndef celBlXml_FACTORY_REGISTERED 
  #define celBlXml_FACTORY_REGISTERED 
    celBlXml_StaticInit celBlXml_static_init__; 
  #endif
public:
 blxml();
};
blxml::blxml() {}

}
