// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_ledges[] =
"<?xml version=\"1.0\"?>"
"<!-- ledges.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.ledgegroup</name>"
"        <implementation>celLedgeGroup</implementation>"
"        <description>CEL Ledge Group</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celLedgeGroup_FACTORY_REGISTER_DEFINED 
  #define celLedgeGroup_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celLedgeGroup) 
  #endif

class ledges
{
SCF_REGISTER_STATIC_LIBRARY(ledges,metainfo_ledges)
  #ifndef celLedgeGroup_FACTORY_REGISTERED 
  #define celLedgeGroup_FACTORY_REGISTERED 
    celLedgeGroup_StaticInit celLedgeGroup_static_init__; 
  #endif
public:
 ledges();
};
ledges::ledges() {}

}
