// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfevolve[] =
"<?xml version=\"1.0\"?>"
"<!-- pfevolve.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.ai.evolve</name>"
"        <implementation>celPfEvolve</implementation>"
"        <description>The genetic evolution property class factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfEvolve_FACTORY_REGISTER_DEFINED 
  #define celPfEvolve_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfEvolve) 
  #endif

class pfevolve
{
SCF_REGISTER_STATIC_LIBRARY(pfevolve,metainfo_pfevolve)
  #ifndef celPfEvolve_FACTORY_REGISTERED 
  #define celPfEvolve_FACTORY_REGISTERED 
    celPfEvolve_StaticInit celPfEvolve_static_init__; 
  #endif
public:
 pfevolve();
};
pfevolve::pfevolve() {}

}
