// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_addon_celgraph[] =
"<?xml version=\"1.0\"?>"
"<!-- addon_celgraph.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.addons.celgraph</name>"
"        <implementation>celAddOnCelGraph</implementation>"
"	<description>CEL AddOn for Graphs</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celAddOnCelGraph_FACTORY_REGISTER_DEFINED 
  #define celAddOnCelGraph_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celAddOnCelGraph) 
  #endif

class addon_celgraph
{
SCF_REGISTER_STATIC_LIBRARY(addon_celgraph,metainfo_addon_celgraph)
  #ifndef celAddOnCelGraph_FACTORY_REGISTERED 
  #define celAddOnCelGraph_FACTORY_REGISTERED 
    celAddOnCelGraph_StaticInit celAddOnCelGraph_static_init__; 
  #endif
public:
 addon_celgraph();
};
addon_celgraph::addon_celgraph() {}

}
