// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_bltest[] =
"<?xml version=\"1.0\"?>"
"<!-- bltest.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.behaviourlayer.test</name>"
"        <implementation>celBlTest</implementation>"
"	<description>CEL Test Behaviour Layer</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celBlTest_FACTORY_REGISTER_DEFINED 
  #define celBlTest_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celBlTest) 
  #endif

class bltest
{
SCF_REGISTER_STATIC_LIBRARY(bltest,metainfo_bltest)
  #ifndef celBlTest_FACTORY_REGISTERED 
  #define celBlTest_FACTORY_REGISTERED 
    celBlTest_StaticInit celBlTest_static_init__; 
  #endif
public:
 bltest();
};
bltest::bltest() {}

}
