// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_blpython[] =
"<?xml version=\"1.0\"?>"
"<!-- blpython.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.behaviourlayer.python</name>"
"        <implementation>celBlPython</implementation>"
"	<description>Crystal Entity Layer Python Behaviour Layer</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celBlPython_FACTORY_REGISTER_DEFINED 
  #define celBlPython_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celBlPython) 
  #endif

class blpython
{
SCF_REGISTER_STATIC_LIBRARY(blpython,metainfo_blpython)
  #ifndef celBlPython_FACTORY_REGISTERED 
  #define celBlPython_FACTORY_REGISTERED 
    celBlPython_StaticInit celBlPython_static_init__; 
  #endif
public:
 blpython();
};
blpython::blpython() {}

}
