// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfwasdmove[] =
"<?xml version=\"1.0\"?>"
"<!-- pfwasdmove.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.move.actor.wasd</name>"
"        <implementation>celPfWasdMove</implementation>"
"        <description>CEL WASD Mover Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfWasdMove_FACTORY_REGISTER_DEFINED 
  #define celPfWasdMove_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfWasdMove) 
  #endif

class pfwasdmove
{
SCF_REGISTER_STATIC_LIBRARY(pfwasdmove,metainfo_pfwasdmove)
  #ifndef celPfWasdMove_FACTORY_REGISTERED 
  #define celPfWasdMove_FACTORY_REGISTERED 
    celPfWasdMove_StaticInit celPfWasdMove_static_init__; 
  #endif
public:
 pfwasdmove();
};
pfwasdmove::pfwasdmove() {}

}
