// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pftrackingcam[] =
"<?xml version=\"1.0\"?>"
"<!-- pftrackingcam.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.camera.mode.tracking</name>"
"        <implementation>celPfTrackingCamera</implementation>"
"        <description>CEL Tracking Camera Mode Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfTrackingCamera_FACTORY_REGISTER_DEFINED 
  #define celPfTrackingCamera_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfTrackingCamera) 
  #endif

class pftrackingcam
{
SCF_REGISTER_STATIC_LIBRARY(pftrackingcam,metainfo_pftrackingcam)
  #ifndef celPfTrackingCamera_FACTORY_REGISTERED 
  #define celPfTrackingCamera_FACTORY_REGISTERED 
    celPfTrackingCamera_StaticInit celPfTrackingCamera_static_init__; 
  #endif
public:
 pftrackingcam();
};
pftrackingcam::pftrackingcam() {}

}
