// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfanalogmotion[] =
"<?xml version=\"1.0\"?>"
"<!-- pfactoranalog.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <!-- @@@ DEPRECATED -->"
"      <class>"
"        <name>cel.pcfactory.move.actor.analog</name>"
"        <implementation>celPfAnalogMotion</implementation>"
"        <description>CEL Analog Actor Movement Property Class Factory</description>"
"      </class>"
"      <class>"
"        <name>cel.pcfactory.move.analogmotion</name>"
"        <implementation>celPfAnalogMotion</implementation>"
"        <description>CEL Analog Actor Movement Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfAnalogMotion_FACTORY_REGISTER_DEFINED 
  #define celPfAnalogMotion_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfAnalogMotion) 
  #endif
  #ifndef celPfAnalogMotion_FACTORY_REGISTER_DEFINED 
  #define celPfAnalogMotion_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfAnalogMotion) 
  #endif

class pfanalogmotion
{
SCF_REGISTER_STATIC_LIBRARY(pfanalogmotion,metainfo_pfanalogmotion)
  #ifndef celPfAnalogMotion_FACTORY_REGISTERED 
  #define celPfAnalogMotion_FACTORY_REGISTERED 
    celPfAnalogMotion_StaticInit celPfAnalogMotion_static_init__; 
  #endif
  #ifndef celPfAnalogMotion_FACTORY_REGISTERED 
  #define celPfAnalogMotion_FACTORY_REGISTERED 
    celPfAnalogMotion_StaticInit celPfAnalogMotion_static_init__; 
  #endif
public:
 pfanalogmotion();
};
pfanalogmotion::pfanalogmotion() {}

}
