// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_tcpnetwork[] =
"<?xml version=\"1.0\"?>"
"<!-- tcpnetwork.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.network.tcp</name>"
"        <implementation>celTCPGameFactory</implementation>"
"	<description>CEL TCP network layer</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celTCPGameFactory_FACTORY_REGISTER_DEFINED 
  #define celTCPGameFactory_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celTCPGameFactory) 
  #endif

class tcpnetwork
{
SCF_REGISTER_STATIC_LIBRARY(tcpnetwork,metainfo_tcpnetwork)
  #ifndef celTCPGameFactory_FACTORY_REGISTERED 
  #define celTCPGameFactory_FACTORY_REGISTERED 
    celTCPGameFactory_StaticInit celTCPGameFactory_static_init__; 
  #endif
public:
 tcpnetwork();
};
tcpnetwork::tcpnetwork() {}

}
