// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_addon_xmlscripts[] =
"<?xml version=\"1.0\"?>"
"<!-- addon_xmlscripts.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.addons.xmlscripts</name>"
"        <implementation>celAddOnXmlScripts</implementation>"
"	<description>CEL AddOn for Defining XML Scripts</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celAddOnXmlScripts_FACTORY_REGISTER_DEFINED 
  #define celAddOnXmlScripts_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celAddOnXmlScripts) 
  #endif

class addon_xmlscripts
{
SCF_REGISTER_STATIC_LIBRARY(addon_xmlscripts,metainfo_addon_xmlscripts)
  #ifndef celAddOnXmlScripts_FACTORY_REGISTERED 
  #define celAddOnXmlScripts_FACTORY_REGISTERED 
    celAddOnXmlScripts_StaticInit celAddOnXmlScripts_static_init__; 
  #endif
public:
 addon_xmlscripts();
};
addon_xmlscripts::addon_xmlscripts() {}

}
