// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfwire[] =
"<?xml version=\"1.0\"?>"
"<!-- pfwire.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.logic.wire</name>"
"        <implementation>celPfWire</implementation>"
"        <description>CEL Wire Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfWire_FACTORY_REGISTER_DEFINED 
  #define celPfWire_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfWire) 
  #endif

class pfwire
{
SCF_REGISTER_STATIC_LIBRARY(pfwire,metainfo_pfwire)
  #ifndef celPfWire_FACTORY_REGISTERED 
  #define celPfWire_FACTORY_REGISTERED 
    celPfWire_StaticInit celPfWire_static_init__; 
  #endif
public:
 pfwire();
};
pfwire::pfwire() {}

}
