// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfdynmove[] =
"<?xml version=\"1.0\"?>"
"<!-- pfdynmove.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.move.actor.dynamic</name>"
"        <implementation>celPfDynamicMove</implementation>"
"        <description>CEL Dynamic Mover Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfDynamicMove_FACTORY_REGISTER_DEFINED 
  #define celPfDynamicMove_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfDynamicMove) 
  #endif

class pfdynmove
{
SCF_REGISTER_STATIC_LIBRARY(pfdynmove,metainfo_pfdynmove)
  #ifndef celPfDynamicMove_FACTORY_REGISTERED 
  #define celPfDynamicMove_FACTORY_REGISTERED 
    celPfDynamicMove_StaticInit celPfDynamicMove_static_init__; 
  #endif
public:
 pfdynmove();
};
pfdynmove::pfdynmove() {}

}
