/*
    Copyright (C)2009 by Eric Sunshine

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

// This header is used strictly for MSVC builds where no celconfig.h file
// is generated by a 'configure' script. It is included by celplatform.h.
#ifndef __CEL_CELCONFIG_MSVC_H__
#define __CEL_CELCONFIG_MSVC_H__

// Presently, no customizations.

#endif // __CEL_CELCONFIG_MSVC_H__
