// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_addon_ledges[] =
"<?xml version=\"1.0\"?>"
"<!-- addon_ledges.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.addons.ledges</name>"
"        <implementation>celAddOnLedges</implementation>"
"        <description>CEL AddOn for Ledges</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celAddOnLedges_FACTORY_REGISTER_DEFINED 
  #define celAddOnLedges_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celAddOnLedges) 
  #endif

class addon_ledges
{
SCF_REGISTER_STATIC_LIBRARY(addon_ledges,metainfo_addon_ledges)
  #ifndef celAddOnLedges_FACTORY_REGISTERED 
  #define celAddOnLedges_FACTORY_REGISTERED 
    celAddOnLedges_StaticInit celAddOnLedges_static_init__; 
  #endif
public:
 addon_ledges();
};
addon_ledges::addon_ledges() {}

}
