// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfgrab[] =
"<?xml version=\"1.0\"?>"
"<!-- pfgrab.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.move.grab</name>"
"        <implementation>celPfGrab</implementation>"
"        <description>CEL Grab Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfGrab_FACTORY_REGISTER_DEFINED 
  #define celPfGrab_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfGrab) 
  #endif

class pfgrab
{
SCF_REGISTER_STATIC_LIBRARY(pfgrab,metainfo_pfgrab)
  #ifndef celPfGrab_FACTORY_REGISTERED 
  #define celPfGrab_FACTORY_REGISTERED 
    celPfGrab_StaticInit celPfGrab_static_init__; 
  #endif
public:
 pfgrab();
};
pfgrab::pfgrab() {}

}
