// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_rulebase[] =
"<?xml version=\"1.0\"?>"
"<!-- rulebase.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.rulebase</name>"
"        <implementation>celRuleBase</implementation>"
"	<description>CEL Rule Base</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celRuleBase_FACTORY_REGISTER_DEFINED 
  #define celRuleBase_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celRuleBase) 
  #endif

class rulebase
{
SCF_REGISTER_STATIC_LIBRARY(rulebase,metainfo_rulebase)
  #ifndef celRuleBase_FACTORY_REGISTERED 
  #define celRuleBase_FACTORY_REGISTERED 
    celRuleBase_StaticInit celRuleBase_static_init__; 
  #endif
public:
 rulebase();
};
rulebase::rulebase() {}

}
