// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfmover[] =
"<?xml version=\"1.0\"?>"
"<!-- pfmover.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.mover</name>"
"        <implementation>celPfMover</implementation>"
"	<description>CEL Mover Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfMover_FACTORY_REGISTER_DEFINED 
  #define celPfMover_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfMover) 
  #endif

class pfmover
{
SCF_REGISTER_STATIC_LIBRARY(pfmover,metainfo_pfmover)
  #ifndef celPfMover_FACTORY_REGISTERED 
  #define celPfMover_FACTORY_REGISTERED 
    celPfMover_StaticInit celPfMover_static_init__; 
  #endif
public:
 pfmover();
};
pfmover::pfmover() {}

}
