// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_bttest_static_plugins_CRYSTAL
{
  _Bind_bttest_static_plugins_CRYSTAL ();
};
namespace { _Bind_bttest_static_plugins_CRYSTAL bind_bttest_static_plugins_CRYSTAL; }

