// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_celtst_static_plugins
{
  _Bind_celtst_static_plugins ();
};
namespace { _Bind_celtst_static_plugins bind_celtst_static_plugins; }

