// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_elcmtest_static_plugins
{
  _Bind_elcmtest_static_plugins ();
};
namespace { _Bind_elcmtest_static_plugins bind_elcmtest_static_plugins; }

