// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_addon_dynworldload[] =
"<?xml version=\"1.0\"?>"
"<!-- addon_dynworldload.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.addons.dynamicworld.loader</name>"
"        <implementation>celAddOnDynamicWorldLoader</implementation>"
"        <description>CEL AddOn for Dynamic World Loader</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celAddOnDynamicWorldLoader_FACTORY_REGISTER_DEFINED 
  #define celAddOnDynamicWorldLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celAddOnDynamicWorldLoader) 
  #endif

class addon_dynworldload
{
SCF_REGISTER_STATIC_LIBRARY(addon_dynworldload,metainfo_addon_dynworldload)
  #ifndef celAddOnDynamicWorldLoader_FACTORY_REGISTERED 
  #define celAddOnDynamicWorldLoader_FACTORY_REGISTERED 
    celAddOnDynamicWorldLoader_StaticInit celAddOnDynamicWorldLoader_static_init__; 
  #endif
public:
 addon_dynworldload();
};
addon_dynworldload::addon_dynworldload() {}

}
