// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfpathfinder[] =
"<?xml version=\"1.0\"?>"
"<!-- pfpathfinder.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.move.pathfinder</name>"
"        <implementation>celPfPathFinder</implementation>"
"        <description>CEL Path Finder Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfPathFinder_FACTORY_REGISTER_DEFINED 
  #define celPfPathFinder_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfPathFinder) 
  #endif

class pfpathfinder
{
SCF_REGISTER_STATIC_LIBRARY(pfpathfinder,metainfo_pfpathfinder)
  #ifndef celPfPathFinder_FACTORY_REGISTERED 
  #define celPfPathFinder_FACTORY_REGISTERED 
    celPfPathFinder_StaticInit celPfPathFinder_static_init__; 
  #endif
public:
 pfpathfinder();
};
pfpathfinder::pfpathfinder() {}

}
