// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfwheeled[] =
"<?xml version=\"1.0\"?>"
"<!-- pfwheeled.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.wheeled</name>"
"        <implementation>celPfWheeled</implementation>"
"        <description>CEL Wheeled Vehicle Class Factory</description>"
"        <requires>"
"          <class>cel.physicallayer</class>"
"          <class>cel.mechobject</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfWheeled_FACTORY_REGISTER_DEFINED 
  #define celPfWheeled_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfWheeled) 
  #endif

class pfwheeled
{
SCF_REGISTER_STATIC_LIBRARY(pfwheeled,metainfo_pfwheeled)
  #ifndef celPfWheeled_FACTORY_REGISTERED 
  #define celPfWheeled_FACTORY_REGISTERED 
    celPfWheeled_StaticInit celPfWheeled_static_init__; 
  #endif
public:
 pfwheeled();
};
pfwheeled::pfwheeled() {}

}
