// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfactorlara[] =
"<?xml version=\"1.0\"?>"
"<!-- pfactorlara.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.move.lara</name>"
"        <implementation>celPfActorLara</implementation>"
"        <description>CEL Lara Actor Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfActorLara_FACTORY_REGISTER_DEFINED 
  #define celPfActorLara_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfActorLara) 
  #endif

class pfactorlara
{
SCF_REGISTER_STATIC_LIBRARY(pfactorlara,metainfo_pfactorlara)
  #ifndef celPfActorLara_FACTORY_REGISTERED 
  #define celPfActorLara_FACTORY_REGISTERED 
    celPfActorLara_StaticInit celPfActorLara_static_init__; 
  #endif
public:
 pfactorlara();
};
pfactorlara::pfactorlara() {}

}
