// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pftest[] =
"<?xml version=\"1.0\"?>"
"<!-- pftest.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.test</name>"
"        <implementation>celPfTest</implementation>"
"	<description>CEL Test Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfTest_FACTORY_REGISTER_DEFINED 
  #define celPfTest_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfTest) 
  #endif

class pftest
{
SCF_REGISTER_STATIC_LIBRARY(pftest,metainfo_pftest)
  #ifndef celPfTest_FACTORY_REGISTERED 
  #define celPfTest_FACTORY_REGISTERED 
    celPfTest_StaticInit celPfTest_static_init__; 
  #endif
public:
 pftest();
};
pftest::pftest() {}

}
