// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfsimpcam[] =
"<?xml version=\"1.0\"?>"
"<!-- pfsimpcam.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.simplecamera</name>"
"        <implementation>celPfSimpleCamera</implementation>"
"	<description>CEL Simple Camera Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfSimpleCamera_FACTORY_REGISTER_DEFINED 
  #define celPfSimpleCamera_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfSimpleCamera) 
  #endif

class pfsimpcam
{
SCF_REGISTER_STATIC_LIBRARY(pfsimpcam,metainfo_pfsimpcam)
  #ifndef celPfSimpleCamera_FACTORY_REGISTERED 
  #define celPfSimpleCamera_FACTORY_REGISTERED 
    celPfSimpleCamera_StaticInit celPfSimpleCamera_static_init__; 
  #endif
public:
 pfsimpcam();
};
pfsimpcam::pfsimpcam() {}

}
