// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfmesh[] =
"<?xml version=\"1.0\"?>"
"<!-- pfmesh.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.mesh</name>"
"        <implementation>celPfMesh</implementation>"
"	<description>CEL Mesh Property Class Factory</description>"
"      </class>"
"      <class>"
"	<name>cel.pcfactory.meshselect</name>"
"	<implementation>celPfMeshSelect</implementation>"
"	<description>CEL Mesh Select Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfMesh_FACTORY_REGISTER_DEFINED 
  #define celPfMesh_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfMesh) 
  #endif
  #ifndef celPfMeshSelect_FACTORY_REGISTER_DEFINED 
  #define celPfMeshSelect_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfMeshSelect) 
  #endif

class pfmesh
{
SCF_REGISTER_STATIC_LIBRARY(pfmesh,metainfo_pfmesh)
  #ifndef celPfMesh_FACTORY_REGISTERED 
  #define celPfMesh_FACTORY_REGISTERED 
    celPfMesh_StaticInit celPfMesh_static_init__; 
  #endif
  #ifndef celPfMeshSelect_FACTORY_REGISTERED 
  #define celPfMeshSelect_FACTORY_REGISTERED 
    celPfMeshSelect_StaticInit celPfMeshSelect_static_init__; 
  #endif
public:
 pfmesh();
};
pfmesh::pfmesh() {}

}
