// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfrules[] =
"<?xml version=\"1.0\"?>"
"<!-- pfrules.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.rules</name>"
"        <implementation>celPfRules</implementation>"
"	<description>CEL Rules Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfRules_FACTORY_REGISTER_DEFINED 
  #define celPfRules_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfRules) 
  #endif

class pfrules
{
SCF_REGISTER_STATIC_LIBRARY(pfrules,metainfo_pfrules)
  #ifndef celPfRules_FACTORY_REGISTERED 
  #define celPfRules_FACTORY_REGISTERED 
    celPfRules_StaticInit celPfRules_static_init__; 
  #endif
public:
 pfrules();
};
pfrules::pfrules() {}

}
