// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfzone[] =
"<?xml version=\"1.0\"?>"
"<!-- pfzone.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.zonemanager</name>"
"        <implementation>celPfZoneManager</implementation>"
"	<description>CEL Zone Manager Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfZoneManager_FACTORY_REGISTER_DEFINED 
  #define celPfZoneManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfZoneManager) 
  #endif

class pfzone
{
SCF_REGISTER_STATIC_LIBRARY(pfzone,metainfo_pfzone)
  #ifndef celPfZoneManager_FACTORY_REGISTERED 
  #define celPfZoneManager_FACTORY_REGISTERED 
    celPfZoneManager_StaticInit celPfZoneManager_static_init__; 
  #endif
public:
 pfzone();
};
pfzone::pfzone() {}

}
