// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_addon_celentitytpl[] =
"<?xml version=\"1.0\"?>"
"<!-- addon_celentitytpl.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.addons.celentitytpl</name>"
"        <implementation>celAddOnCelEntityTemplate</implementation>"
"	<description>CEL AddOn for Entity Templates</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celAddOnCelEntityTemplate_FACTORY_REGISTER_DEFINED 
  #define celAddOnCelEntityTemplate_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celAddOnCelEntityTemplate) 
  #endif

class addon_celentitytpl
{
SCF_REGISTER_STATIC_LIBRARY(addon_celentitytpl,metainfo_addon_celentitytpl)
  #ifndef celAddOnCelEntityTemplate_FACTORY_REGISTERED 
  #define celAddOnCelEntityTemplate_FACTORY_REGISTERED 
    celAddOnCelEntityTemplate_StaticInit celAddOnCelEntityTemplate_static_init__; 
  #endif
public:
 addon_celentitytpl();
};
addon_celentitytpl::addon_celentitytpl() {}

}
