// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfengine[] =
"<?xml version=\"1.0\"?>"
"<!-- pfengine.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.region</name>"
"        <implementation>celPfRegion</implementation>"
"	<description>CEL Region Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfRegion_FACTORY_REGISTER_DEFINED 
  #define celPfRegion_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfRegion) 
  #endif

class pfengine
{
SCF_REGISTER_STATIC_LIBRARY(pfengine,metainfo_pfengine)
  #ifndef celPfRegion_FACTORY_REGISTERED 
  #define celPfRegion_FACTORY_REGISTERED 
    celPfRegion_StaticInit celPfRegion_static_init__; 
  #endif
public:
 pfengine();
};
pfengine::pfengine() {}

}
