// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_celtst_static_plugins_CRYSTAL
{
  _Bind_celtst_static_plugins_CRYSTAL ();
};
namespace { _Bind_celtst_static_plugins_CRYSTAL bind_celtst_static_plugins_CRYSTAL; }

