// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_elcm[] =
"<?xml version=\"1.0\"?>"
"<!-- elcm.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.tools.elcm</name>"
"        <implementation>celELCM</implementation>"
"        <description>CEL Entity Life Cycle Manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celELCM_FACTORY_REGISTER_DEFINED 
  #define celELCM_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celELCM) 
  #endif

class elcm
{
SCF_REGISTER_STATIC_LIBRARY(elcm,metainfo_elcm)
  #ifndef celELCM_FACTORY_REGISTERED 
  #define celELCM_FACTORY_REGISTERED 
    celELCM_StaticInit celELCM_static_init__; 
  #endif
public:
 elcm();
};
elcm::elcm() {}

}
