// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfmeshdeform[] =
"<?xml version=\"1.0\"?>"
"<!-- pfmeshdeform.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.meshdeform</name>"
"        <implementation>celPfMeshDeform</implementation>"
"	<description>CEL FFD Mesh Deform Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfMeshDeform_FACTORY_REGISTER_DEFINED 
  #define celPfMeshDeform_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfMeshDeform) 
  #endif

class pfmeshdeform
{
SCF_REGISTER_STATIC_LIBRARY(pfmeshdeform,metainfo_pfmeshdeform)
  #ifndef celPfMeshDeform_FACTORY_REGISTERED 
  #define celPfMeshDeform_FACTORY_REGISTERED 
    celPfMeshDeform_StaticInit celPfMeshDeform_static_init__; 
  #endif
public:
 pfmeshdeform();
};
pfmeshdeform::pfmeshdeform() {}

}
