// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfdynworld[] =
"<?xml version=\"1.0\"?>"
"<!-- pfdynworld.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.world.dynamic</name>"
"        <implementation>celPfDynamicWorld</implementation>"
"        <description>CEL Dynamic World Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfDynamicWorld_FACTORY_REGISTER_DEFINED 
  #define celPfDynamicWorld_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfDynamicWorld) 
  #endif

class pfdynworld
{
SCF_REGISTER_STATIC_LIBRARY(pfdynworld,metainfo_pfdynworld)
  #ifndef celPfDynamicWorld_FACTORY_REGISTERED 
  #define celPfDynamicWorld_FACTORY_REGISTERED 
    celPfDynamicWorld_StaticInit celPfDynamicWorld_static_init__; 
  #endif
public:
 pfdynworld();
};
pfdynworld::pfdynworld() {}

}
