// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_ui_inventory[] =
"<?xml version=\"1.0\"?>"
"<!-- ui_inventory.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.ui.inventory</name>"
"        <implementation>celUIInventory</implementation>"
"	<description>CEL Inventory UI</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celUIInventory_FACTORY_REGISTER_DEFINED 
  #define celUIInventory_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celUIInventory) 
  #endif

class ui_inventory
{
SCF_REGISTER_STATIC_LIBRARY(ui_inventory,metainfo_ui_inventory)
  #ifndef celUIInventory_FACTORY_REGISTERED 
  #define celUIInventory_FACTORY_REGISTERED 
    celUIInventory_StaticInit celUIInventory_static_init__; 
  #endif
public:
 ui_inventory();
};
ui_inventory::ui_inventory() {}

}
