// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pflight[] =
"<?xml version=\"1.0\"?>"
"<!-- pflight.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.light</name>"
"        <implementation>celPfLight</implementation>"
"	<description>CEL Light Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfLight_FACTORY_REGISTER_DEFINED 
  #define celPfLight_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfLight) 
  #endif

class pflight
{
SCF_REGISTER_STATIC_LIBRARY(pflight,metainfo_pflight)
  #ifndef celPfLight_FACTORY_REGISTERED 
  #define celPfLight_FACTORY_REGISTERED 
    celPfLight_StaticInit celPfLight_static_init__; 
  #endif
public:
 pflight();
};
pflight::pflight() {}

}
