// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_pfdelegcam[] =
"<?xml version=\"1.0\"?>"
"<!-- pfdelegcam.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>cel.pcfactory.camera.delegate</name>"
"        <implementation>celPfDelegateCamera</implementation>"
"        <description>CEL Delegation Camera Property Class Factory</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef celPfDelegateCamera_FACTORY_REGISTER_DEFINED 
  #define celPfDelegateCamera_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(celPfDelegateCamera) 
  #endif

class pfdelegcam
{
SCF_REGISTER_STATIC_LIBRARY(pfdelegcam,metainfo_pfdelegcam)
  #ifndef celPfDelegateCamera_FACTORY_REGISTERED 
  #define celPfDelegateCamera_FACTORY_REGISTERED 
    celPfDelegateCamera_StaticInit celPfDelegateCamera_static_init__; 
  #endif
public:
 pfdelegcam();
};
pfdelegcam::pfdelegcam() {}

}
